# Generated by Django 4.1.2 on 2022-10-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="sum",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="balance",
            name="sum",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
